### ISSUE TITLE
site to site tunnel

### ISSUE THREAD

**Issue by Perchework** [cloudycube/docker-strongswan#7]
Hi,

Did you have an idea if it's possible to contact the client from a container in the same docker network as the VPN container ?

Sample:
my workstation have the ip 10.1.1.201 (and a virtual ip 10.0.0.2 from the VPN)
The VPN container is on a network (10.1.2.0/24) and i can access every service on that network from my workstation.
I can ping my workstation from the VPN container, but I can't ping from an other container in the VPN network.

At the end, I need to create a site to site VPN tunnel between a corporate network and a new docker swarm cluster.

I will love to contribute to make this new feature available.
Did you have any advices or ideas ?

Thanks
Thomas.

**Comment by ravenpride** [comment]
Hi Thomas,

could you please post your piece of code to start the container? - Or your docker-compose.yml, if you use one. I'll try to understand what's going on.

You've observed that the VPN client can communicate with services in your docker network, but you cannot communicate from one of the containers - other than the strongswan container - with the VPN client. That said, I assume that is a packet filter issue rather than a routing issue.

If you're using the Windows VPN-Client, please try to disable the Windows firewall to check whether it blocks the connections. That is usually the case, if your VPN is configured to be a "public" network. Windows firewall rules are very restrictive in this case.

Greetings,
Sascha

**Comment by ravenpride** [comment]
Oh, almost forgotten...

The stronswan container is designed to work for the VPN roadwarrior scenario.
You can see the roadwarrior scenario [here](https://www.strongswan.org/testing/testresults/swanctl/rw-cert/).
The site-to-site scenario is a bit different, see [here](https://www.strongswan.org/testing/testresults/swanctl/net2net-cert/).

Generally, it should work, but we have to think carefully about the differences.

**Comment by ravenpride** [comment]
@Perchework Do you have any thoughts regarding this issue?

**Comment by Perchework** [comment]
@ravenpride I'm still working on it, I come back later with more information.

**Comment by ravenpride** [comment]
Due to one year of inactivity, I'll close the issue now. Please feel free to re-open it, if necessary.
